[project]
name = "mtcli-vap"
version = "1.2.2"
description = "Plugin mtcli do Volume At Price"
authors = [
    {name = "Valmir França",email = "vfranca3@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10,<3.14"

keywords = [
    "trading",
    "volume-at-price",
    "volume",
    "metatrader5",
    "mt5",
    "cli",
    "acessibilidade",
    "screen reader friendly"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Financial and Insurance Industry",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Office/Business :: Financial :: Investment",
]

dependencies = [
    "mtcli>=3.7.0",
    "click (>=8.3.0,<9.0.0)",
    "metatrader5 (>=5.0.5370,<6.0.0)"
]

[project.urls]
Homepage = "https://github.com/vfranca/mtcli-vap"
Repository = "https://github.com/vfranca/mtcli-vap"
Issues = "https://github.com/vfranca/mtcli-vap/issues"
Documentation = "https://vfranca.github.io/mtcli-vap"

[project.entry-points."mtcli.plugins"]
mtcli-vap = "mtcli_vap.plugin:register"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^6.2.1"
pytest-mock = "^3.15.1"
ruff = "^0.14.1"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
pymdown-extensions = "^10.16.1"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
  "E",    # Estilo
  "F",    # Lógica
  "B",    # Boas práticas
  "I",    # Imports
  "UP",   # Upgrade
  "N",    # Naming
]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["mtcli", "mtcli_vap"]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
